apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datapipe-storage-local
  labels:
    project: datapipe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi