apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datapipe-storage-local
  labels:
    project: datapipe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 4Ti
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: retain-local-path
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain