apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datapipe-storage
  labels:
    project: datapipe
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 300Gi