apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  labels:
    app: debug
    project: datapipe
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
        project: datapipe
    spec:
      volumes:
      - name: datapipe-storage
        persistentVolumeClaim:
          claimName: datapipe-storage
      containers:
        - name: debug
          image: paulandrei/datapipe:0.7.3
          imagePullPolicy: IfNotPresent
          command: [ "sleep" ]
          args: ["infinity"]
          volumeMounts:
          - mountPath: /datapipe/
            name: datapipe-storage
          env:
            - name: PG_HOST
              value: datapipe-db
            - name: API_URL
              value: http://text2lang:80/text2lang
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datapipe-db-secret
                  key: POSTGRES_PASSWORD
