apiVersion: v1
kind: Service
metadata:
  name: datapipe-db
  labels:
    project: datapipe
spec:
  type: LoadBalancer
  selector:
    app: datapipe-db
  ports:
  - name: postgredb
    port: 5432
    targetPort: 5432
