apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage  
  labels:
    project: datapipe
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
