apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher
  labels:
    app: fetcher
    project: datapipe
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fetcher
  template:
    metadata:
      labels:
        app: fetcher
        project: datapipe
    spec:
      volumes:
      - name: datapipe-storage
        persistentVolumeClaim:
          claimName: datapipe-storage-local
      containers:
        - name: fetcher
          image: projecteaina/datapipe:latest
          imagePullPolicy: IfNotPresent
          command: [ "python", "-m", "fetcher" ]
          volumeMounts:
          - mountPath: /datapipe/
            name: datapipe-storage
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PG_HOST
              value: datapipe-db
            - name: YT_AUDIO_DOWNLOAD_PATH
              value: /datapipe/audio/youtube
            - name: YT_CAPTION_DOWNLOAD_PATH
              value: /datapipe/caption/youtube
            - name: CCMA_AUDIO_DOWNLOAD_PATH
              value: /datapipe/audio/ccma
            - name: CCMA_VIDEO_DOWNLOAD_PATH
              value: /datapipe/tmp/video/ccma
            - name: CCMA_CAPTION_DOWNLOAD_PATH
              value: /datapipe/caption/ccma
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datapipe-db-secret
                  key: POSTGRES_PASSWORD
